### ISSUE TITLE
Add Twitter as a provider

### ISSUE THREAD

**Issue by kurtfunai** [dyatlov/go-oembed#3]
Twitter also supports oembed! It would be great to have this added to the provider list as well :)

https://dev.twitter.com/web/embedded-timelines/oembed
https://publish.twitter.com/oembed?url=https://twitter.com/TwitterDev

**Comment by dyatlov** [comment]
Right, I updated providers.json from official site: https://github.com/dyatlov/go-oembed/commit/203722a3abcf37841fb4ea1b3258bf954c76be91
Now twitter is there :)

**Comment by kurtfunai** [comment]
Wow thank you for the quick response!
